server:
  port: ${SERVER_PORT:8082}

spring:
  profiles:
    active: loc
  application:
    name: write
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/write
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

transform:
  api:
    url: ${TRANSFORM_URL:localhost}:8083
