server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: write
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/write}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
