server:
  port: ${SERVER_PORT:8082}

spring:
  profiles:
    active: loc
  application:
    name: write
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/write
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: 211.254.213.33:9092
    consumer:
      group-id: write-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  swagger-ui:
    path: /swagger-ui.html

transform:
  api:
    url: ${TRANSFORM_URL:localhost}:8083
