server:
  port: ${SERVER_PORT:8082}

spring:
  profiles:
    active: loc
  application:
    name: write
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/write
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

transform:
  api:
    url: ${TRANSFORM_URL:localhost}:8083
