server:
  port: ${SERVER_PORT:8081}

spring:
  profiles:
    active: loc
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/auth
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
