server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: transform
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/transform}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
