server:
  port: ${SERVER_PORT:8083}

spring:
  profiles:
    active: loc
  application:
    name: transform
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/transform
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

chatgpt:
  api:
    url: https://api.openai.com/v1
    key: ${OPENAI_API_KEY}
    model: gpt-4

history:
  api:
    url: ${HISTORY_URL:localhost}:8084
