server:
  port: ${SERVER_PORT:8083}

spring:
  profiles:
    active: loc
  application:
    name: transform
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/transform
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: 211.254.213.33:9092
    consumer:
      group-id: transform-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "com.ktds.templify.write.dto.TransformRequest:com.ktds.templify.transform.dto.TransformRequest"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  swagger-ui:
    path: /swagger-ui.html

chatgpt:
  api:
    url: https://api.openai.com/v1
    key: ${OPENAI_API_KEY}
    model: gpt-4

history:
  api:
    url: ${HISTORY_URL:localhost}:8084
